### ISSUE TITLE
Bug: changing user status in the info panel not working

### ISSUE THREAD

**Issue by doenich** [R-Andrei/Teamscord-Client#9]
Steps:

  1. Access the web page
  2. Enter login credentials
  3. Click the Login button
  4. Click the user image in the info panel
  5. Select any status

Status not changed after step 5.

**Comment by R-Andrei** [comment]
Bug resolved in last merge. [9be821a](https://github.com/R-Andrei/Teamscord-Client/commit/9be821a861b77d923b273058a940a1d270614375)

Closing issue.
